kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:Urp4GRH7rtePjytt0MNP0W5QeAE/FARMcOPH4qzLx3aQ4GaPJNyZ08Mi/6dRGgo=,iv:7pfH9jWtqbXjbFkW/T1HbMC0nJVLsuR6Gw1qjJpZ6lQ=,tag:/foZ7US5sSFtAHuF44NrmQ==,type:str]
    github_user: ENC[AES256_GCM,data:0YIY9yU8qT4=,iv:3maLyBK7uaS5aWbA+rnK6qk+MbYtVq7Q7O4upfNyYYk=,tag:VIyrYqYobAaoKT66DKFc5A==,type:str]
    github_api_token: ENC[AES256_GCM,data:LA7rg+SA1klsDalrN9jZeMZ8LA0hopq4w55hPWDdWAPlzjZU0qsHpA==,iv:35bSgPXog/cZKWuQpj9jSyG+ivCtDmh3JkaAqOzIqc0=,tag:9nc/rGqfbH/9fDyufpO0ew==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:xDCy2KskXjnBaCDR,iv:bsp0bgQgDNGLp2UTJURELqAQWXB7PUZXW0TgEthBNl8=,tag:5DoSdU1pnI3gMDzO7SRRYg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:ipgRC7nkRANk,iv:fpUPtP+EZSrg9IaiuN3k7ZRLixI4DWn6K1exncWup9w=,tag:mJdUfQvyZjBPmYeGVfI6ug==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:AoGlIki/z3A2o0jDgQ==,iv:xhFhPVzEZvYEJuQbef76wCG8bR6mSkxyTSL2hDf3oaw=,tag:BFBzej9vqAQ/WS5ujk6LBQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:qtUPHec=,iv:yCcsC9+JJpbIjQ4xEF9DTOK4Zrxu6uM2Td87uMEEFbI=,tag:teeazeEfu6HfTKJaXVLVxA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:rwR6muyN4nN2,iv:I/O4gCWjuh/uzbUceICAEv7ovXof24cTDLrkh33xikM=,tag:6KPzJu9eJ62OYPcE4mQeqw==,type:str]
    objects_host: ENC[AES256_GCM,data:sZV5p8J7Ds88HYEmbg==,iv:7Ugxm2l7oCYgZLaIs6z6Hgz+RXPlgPJXlopwcCaGfsU=,tag:hg1ddnPMT/b43QdRaU/oGQ==,type:str]
    objects_port: ENC[AES256_GCM,data:Ve4=,iv:Bm2OOKQ0a3ruEk2+FgiBMWQ5rLdBaQRGsTrez/yMtrk=,tag:QsXqF1+F4g2ZnOpUlKQ8Bw==,type:str]
    objects_region: ENC[AES256_GCM,data:C+mfmIIIgNL/,iv:I5X/myYmNh98im4zQYnH3cgWYDi9SfWA87JUlCh7R5g=,tag:SK+3gUZKhy7TLdfg8iYcCw==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:iET8h+Q=,iv:kK+luocTDW5ZsUZt/w/TJMP/6/kdnz9wk0QkfNGtU+s=,tag:vL988w2dCf7wRzR/LdwloQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:tzlR5bAZX/O01YD0Um6UDz6JZWj7H00IOouwYA5jRC4=,iv:XW6VwnvHlNlA0m6uJmCtyY6vU/wgd71zNXRw5NOjXkw=,tag:/MP9JVn2BMBuvcchQL2RDg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:4gCXvCUjfQeN3B0kUIvwEAtcqipUpdqWcr1OaQqAkVA=,iv:nh8KAbf08EqMJ3vNEaPCCTNgfgo4U/0jT4sqHyRdMTo=,tag:rhDBK4v3UKzdJs7dX2uI/A==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:smfcx8b0SPFQf1cFHdFjuKPAdpEMtPjzg+EA,iv:2ZCqCGLpETdVSok+qRT1bnwKu2eq5CMQcM6vVqcfO5I=,tag:6759tEXJJmKZp/y0rzTEmQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:Oqvfp+5g8EOmsEM1m7De/g==,iv:3JFZk8libAESVr9bvwFT67anStgktRB9BeidK4kqwgo=,tag:bS8onafP0Xc1y/H8CeaY1w==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:vvZayCSuJd5ltF3oibw4LawNURdLqrjBv2o=,iv:ABMI3CbQzipISdppAky8/4iyPNwZXE0rXwh0UiPy1Vo=,tag:cPHE5p+bmI0kenB2EP+LUw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:vwsXVf7mgdOYS++sh2/fkpbQRGVtA9EI4b0=,iv:So3t2MSJVawZgeXIyhCHYsC7nd+2AI0DFODeAHsekd0=,tag:5AGCxz4TcaVElAYucvxqlw==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:QSGzSjyBqPCkN9eT00jr8A6Qi/tt8wPzZomqZp35BbdNNSKnQaM9KjyNKfSrIEoij7TX621pgUulQwYr,iv:1YBL9VN6p8lG7i1znPcBGtt0xCQqAjANDGj4EQwKvV0=,tag:VNvfeSkS6UwAadStculb+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ds04577equqkjjmm3qs2t92u59fq4kgzqcq3khlhsg8y2p6m033qhfhj4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMDZrMXF4NEdzVHI2RDc4
            NzlzUHBqWUZsWEd6eHI4NlhGZjUvaHlpV0RBCmZ2WXdGcjN6U21ROGVKanBmUGNx
            YTVWQnl3SlgvTnVVWFhhYi9kekVVREEKLS0tIGVGYTZXWTRKakEyMVVnUi9iZmdv
            d3ZMbjFvZ2V1cG5GcDI5Nk1Mem5RSW8KPDqdB1Sd1vnMVqE/GNf6Bbdy/hh1bcmK
            dx1fmBI7ZD9wUnBhkqjS0cW79O5YaFRAzxBZfbT/MV44TFAE5Fs3Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-03T14:57:16Z"
    mac: ENC[AES256_GCM,data:iDvIh88GefrwDBl3sGDwWY4WlsQgP+kMHAkcH7PZQ2xeWWBQbhDHou0lolzbg/35ot8CvMoXBuugfCN2UmsEY9vnGkeVUumyaDU6tEWLWyQR8QIDuQYnYHXELg8z34VNgqWzRQx4V1fxjkFNWgd1wSAozKTN+4sE2qNBsmF1Sts=,iv:yPIOi+grjEO6AG8r9lowM8mnywFyPdA1lb111VGwQcw=,tag:pZLrEsA2YEW94xiI0ccm9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.9.0
