kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:Gy5BgCz4VNJqmadc6j/TbTF28GTl/YmIyKTd01+Jw0GlazwmWArnNTwJekif8Xs=,iv:/fVFgPuCu31uWZHHZhlf4OMv/noy7mdCMGJv2boh0a0=,tag:2RuzGYOMRC/fY906R2Fevg==,type:str]
    github_user: ENC[AES256_GCM,data:9Yf56Fu9HPA=,iv:MTVrmvVardVDJ1d5JNV4T8eSc/ZSPTeyomAJwNMV0Xw=,tag:9EI5VO/HnMw1c7p+3aSpIg==,type:str]
    github_api_token: ENC[AES256_GCM,data:XrH4a7qX6B4z4pMkVEo8kDSGHOa+5vLZ/cDmxLeU+60YTaSfHq74Kw==,iv:Xn4tmB5W/Kv/pt5MJG6u/wbtqkZA5k6hBnDnC7TtbkI=,tag:lTHpgnixxLgeIXQSxsEyww==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:VtT1Xd0jIXas4pJw,iv:t+z733eSH4XN/T571spOXaBK8gMzSryzlATRkQLfP2M=,tag:JzOILobCTppIynGlkUI/KQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:j09yPCGOj7vn,iv:gukU3vQ6E8erDeIWrOwpGGllaK4LEiyXma7lScCfZp0=,tag:ZBF9+RxTi2EDwkCsUbCSFg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:zt+EhwofQtPBCx4YAw==,iv:lS/GLLGTLimavM2EMNoOSfHod/fl/YPoi2V0nCP82qg=,tag:DygKDxgotsjMfKYeS8HDaw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:wvSGURM=,iv:JTQd738iddzQMuPX0DZCKEu7GAgDMtWkdvwrEylygY4=,tag:HR469EmQumhgRJ0E54oHlQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:Dgk+NXHgPhX5,iv:ntP9fzS0nUfmc+UPxu3kYe/fhgU4HBalIC+LTLtOIrg=,tag:t6KK+pjOtLIYiv5JtP/2rA==,type:str]
    objects_host: ENC[AES256_GCM,data:QV0etQsPycM6K54AUA==,iv:ATl9quxT3nk+x+t/RrjTzkdmnX1DVJwBpet/v3qvhoY=,tag:vuISnufrQIF/PlZ4/gcnEQ==,type:str]
    objects_port: ENC[AES256_GCM,data:VtE=,iv:HGoCeTCb0e/EZFgL7O2oY8WL2Zt+TUSOaXSSh6mcyVA=,tag:KieSMLL0x5E8ks1MriTYnw==,type:str]
    objects_region: ENC[AES256_GCM,data:fevdrCour2QI,iv:Qgk1EzIWYy+VVKOvsZUx/m+vKjko/bkH06Tbu9tPBvQ=,tag:Sb5SEx4Metm0qtokA8bnpQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:O/fbIrQ=,iv:I6NHJmaaqI5tltqVff7ELaOF07CCYVY/tPtmfiL25K4=,tag:O9SI3+GgYxIqom0rfHcE6g==,type:str]
    objects_access_key: ENC[AES256_GCM,data:AV/dvGvvi+7SV6sTogNI5bvhw7xj3gNlIgo02ByhI5U=,iv:XvYU9XtdQ6zfy2G13EkMvAq4edo9lXfW5CKGr/1rLyk=,tag:OFIVL0ogJx9yZic5ACr45Q==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:VkeYDBJ6drF17QfImphyiVPuuDlBwqyznEMnw2gG4DE=,iv:7KGjKu4I/77XfAnLAWwBEUkxVDio/wdf8WbVG7KP2Ko=,tag:vqyQnHZKmZeRmpIUX6fqgw==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:+G0T2tD1QGkikE+bg1nwk0GXtRUui39xf72p,iv:k2rbgM4nKrdGKfMwnpKtHeTOpSwxIHWIzgIOAzMcwUQ=,tag:1TyG/Dx2H6UlNQFU03pO7g==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:rNpnoHsvYCRbdH4mRW39rw==,iv:wPmlzvXMu3dgxqmzLmkFi7sVeeUPljUeap3+oYNN3tw=,tag:0DgfuYY4mGwjETGivQ8C/w==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:WHwL0Mhft3ABYau5Y1BM3H74Tgn/CIVasw9VJPqY,iv:BLvgUd75rDTbhbB1R+TCZQW+PZHMy5M+qQfptltLC/s=,tag:6JNR/YmWegLNZQSQ2/qfhw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:9TgHZ5CiMVzgED6pJDoo3A6Qs8bDn4pZWghHxU2B,iv:vHBBKU7Nus+fwtG24MjF6mufeYUycO3m8MrrjToJ5N4=,tag:BUVsmBfAH6FNyEplouS1Ag==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:NBNtnFyYnC45zW0SfoDeyQ==,iv:ubnjZUdQToeX8rd4jbOOPc3M63BAscHka5q/GBSMGdc=,tag:9LU4yXyXGXNfJfyfgLXmqg==,type:str]
    istio_vip: ENC[AES256_GCM,data:ElGjuNuoWpM1wAsXiA==,iv:Ut8bzWbepiYxNoYD9UpwbdfniR13zdMIFO2I+wp0LCY=,tag:Nrbwtc30xYTblAphyWpmMQ==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:MgzhEw9KE5PRVzkqXyTu5vGRozGf2/Hyb74axtK4,iv:zJsKDYaPc+iVDnhhtXEycAFklUHpiXg95Xe4Apep8x0=,tag:uTucCKX5LQDhnK6DNVnGqg==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:I+htt+j281xKeUhYS9LBIQgF55l0J1MLoZwK3r3ipCRwCdttHMBqzx2jUJ2ijvQFbXi5f1F32Wies1FZ,iv:8lanAj0urVUa2QjOnKTo3brrxatSctKaNgoPIYGLFc0=,tag:JsXUEgUqon1UMaPqOwlOCQ==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:9XMiXquqUQzAuYSSDjh8ToDxur7bmiS3iMVY+Z6EbdTfvEnHHg==,iv:22Smeq9KEfDSh0Cs/lP5hz+SQWxkd0zFeSSBI3n7Ot8=,tag:a/27HGn0fn0PzmQ8dagLLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ds04577equqkjjmm3qs2t92u59fq4kgzqcq3khlhsg8y2p6m033qhfhj4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOWkwdkVzZ2QxV2s1THN6
            czl5L0NFaWllVDZIRVpjejBSM2xlWncwN0IwCkYrMFFzMWp6Nmcwcis1c2EzNGNR
            aExSOEJ5dVpMWHhMYlVrYVIwUkxWcUUKLS0tICt3N3hPQUtLTWV2cmp1anZmSjQz
            Q3pDSkVVc2J4TkpDcWtjN2c1eXNSZ1kKwMaQX8K3J0LI8iOT3W6obntgXqmavQg4
            kwTXMQLTu3hQ9udkB1OiErtVgGXJhno2p3mMo85hjOXto0rtIw/Mug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-03T19:52:05Z"
    mac: ENC[AES256_GCM,data:s8S/DsNVd1qtiq2KHcKTZUgErUmnx8AWGXe3KUAdv5y4mq6gxvZBEIhhbH1nhyUbi096CplHwdMcKYvxOIMtt6iseEc+HFKdi0DiuMt1XKKd4QMmlpamBmnaRE7zdM6PXpPktCZBd4m+z5ZHqA4fle1bupkfdegDGi1GG7iFyqk=,iv:lXZ9nrff2rb4AE+nF2M75CIRPCeewcjg/+rF9a30lSc=,tag:RMUpXw6gHKqesxxgkgKSlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
