kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:hslWOY8FBMfdHZL0zeUTxy4pHLQSyZ04j7vaPFYcy3r6/ZWC3iU/lxJOe4s/LX0=,iv:0xDw5Uj0Uo2PYDZEp9KFZ5gBCX7KZ5XBzOnA0uewdOs=,tag:rbK8Nr9lTBQja/SfMUCSrA==,type:str]
    github_user: ENC[AES256_GCM,data:/fjAPQRMjLA=,iv:pXh0GCBoxRrTKoe9CfhlZfsVs7K5o7kx3D5skHljN/s=,tag:X6TNyiR2RCAx5ABzVWWg4Q==,type:str]
    github_api_token: ENC[AES256_GCM,data:1ZSBq2lDHoc0odYUafwcIDsXwQYwr276Pk4COD+gkrJdVB3izVxA9Q==,iv:U+li2UDf5qgiQHAJTZZNSsQCe+8CuZKZxJCnFrtgsLI=,tag:5sJS34tNME/uPl5xlAY7GQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:M8Vlm9DC982F9V09,iv:QTXRgprm/yaLGeuLcXGjbAE5bISU4Wnrg7x7GYJKrN8=,tag:i18s0knvAcSMsr4oXTp7OQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:MBYf1jgJ0ape,iv:4wO1+gwp2UxHWH2ALui8yF7uqNwqz/3bpM2QuWx+ivM=,tag:g7mggqckP0rBTy9i0A7LKg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:7grz8QvBXVhsYSigjg==,iv:p5BRdtQrnBEZ6alk1nLkzq+r9uxfZmrjsdNK66Z01rw=,tag:6/CH2R5c0sEsEjnGeZZ8Fg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:eFogVpA=,iv:ePeXVJdXZFP8JqfKWfvitXIw9dUdVdgvSubGHEHLDWg=,tag:sUJbKK01/7HzWEC0Nw743g==,type:str]
    prism_central_password: ENC[AES256_GCM,data:ZWtY3L5XT7qy,iv:2S3PhMTmMfAYMQ2ECnZum5wP2WXwJrh1zM+fexJMVpw=,tag:IvNylU0sRsblKN8D+vwJ2A==,type:str]
    objects_host: ENC[AES256_GCM,data:n/iYtYNMY9aLW/WyCA==,iv:W5Q88WJNqyK2EFnCUOrgsZvsvUSdKXKPmsRwK4Xqm1k=,tag:ylkdRB+ootepjaLtYZb78Q==,type:str]
    objects_port: ENC[AES256_GCM,data:19c=,iv:adOEQ+LDfjDHtbG5HrvB5QX27vlgZbN1ifJAgnbUvh0=,tag:LjLAXsvAm9eIGuSYY5xbtQ==,type:str]
    objects_region: ENC[AES256_GCM,data:2fkbPerFpMJd,iv:ceV3/NLmhyCaJhF0C+VAZHsMzKswyPoIWX1mdq747WE=,tag:1E+WRvGfSm2H4OvCaIRseQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:0pntK6g=,iv:w6HhtwxxWCwHVhqhtOZzhhViyKR4yE3+gaXaE/PLNl4=,tag:4FYPVz8MWiNx3z2HMtn9Yg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:s/w2JG3G6bpORRWhBPBbn/G92aHa/UH0zWN7MIWyBwM=,iv:TITu513REDl9EoGuHYeDUJIw5dU4G+ti6gzY+WarVzg=,tag:l5C7m//tEPCcnpJmiXm61Q==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:A7TXliBNt97EmkgkJzz0xFQ0VFaob/qcjXA1zfK/zas=,iv:kb4D28mdV0ElYoQLOCV5vulLUxFkddtXIQQg/ZI9qow=,tag:9w9LYEYo/5LlkENHE6961A==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:kJTEuB0e98UIO6mPOjYdbaC55IEOoNflHXVS,iv:N8Pd/aKHJ9l7xkgKP/I3UMr7sGUNAER/QZHPlIaGzm8=,tag:wl/fhPoZZ1hgYTE3W/aCVA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:I8l5UOUy3Hf/rodAOvtkOw==,iv:+RDThlUlseGSHmXhXNdX0WKL/DjaYe5Xicd+bq2hf4M=,tag:I4BiQdsqhb71tc6TeunH/g==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:Af55+3gY5UoTpgN8wehD82LnGoEXjtupgoGhM5x0,iv:MyQ8osaE6U3/G929nuTQmcgjrodueWy/R24c9fmduD0=,tag:bcAJtHcOaa0CnMkhKG2gMg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:qbu/jzJlOGFP7uqkqmL3stQAkpupe7vT4Y/Uxj5a,iv:NFY64NjsNemzKBDFrr1OuUbv41wYvk0zQdgE19Nt8ao=,tag:BvWPlJiCVhop12fZQrQEZw==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:RRPpozr6+xmFCDWmIAA03w==,iv:CEML/Ju0IzdJ1T1lRf1YS7IpVkDRZMm0JbQ4bXvLiWI=,tag:lIldOuMMng19w4Ii7TlZqw==,type:str]
    istio_vip: ENC[AES256_GCM,data:7ElFDikLTCeXd6Z4HA==,iv:J83PkyrXFBTHRO2sCiNpFvVtMAbxdZqf/fFiJKiNQRQ=,tag:cRcZVRy2gtFZU4eaBy+G1Q==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:8zgq7wz2lUS88fbJBmytLucRNuB6fBnWi/TjwCLh,iv:QG0AC+DiiStJl6UiZhHrebMIi4n+PLseL5TL8Y+5/RQ=,tag:zA/xYfS2EoVRSdY32NdcaA==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:GWX6n9dpXfS8k8EEyUPV0V/Gba3ZVGs0CorMn6ZNlJ3+iq5Z619ksJn/IPyfLMAD+iPlX2fDKHeENCj5,iv:A0VdcwqHgsaNybACfTrmMVIxlMsn9u0FoNouQ+HbTFA=,tag:apLtVjxBZEhQaNoNOdbJyw==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:VUWCJj+U7iDSq32eTRf9kQP6woeCx9/kCSEBHYYprDBLaFK9gw==,iv:eOdNseAjFT2URb8Z5d9enjVvFf9bHoxKCHFfQAQ6U9Y=,tag:tkoYLyJfhDE4xw2C8qdXag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ds04577equqkjjmm3qs2t92u59fq4kgzqcq3khlhsg8y2p6m033qhfhj4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dXlCUXUzOVVFTDl0bTdP
            SkhsNXFYODVlL2lzdzN6bnFVTU4xcUtPSzNVCmZwRlZYY1VqWWhiWjNnaDBMSjM2
            VE0zT1BtVnZMK2NjRERnSzZuL2wwakUKLS0tIHlHK2lCT0hoM0t0c1FSZTh6ZTho
            WVNpZm16SHRIR25EYUNOOUYxVnNER3cKAZGwlHh4RY5cBt595bkMxN4+6Sps3Vto
            vemYyMSaVlFegv10oVVL7Zv9lJxka/+rBEYWlCwsA3R9p8BFCJJcEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-03T19:38:33Z"
    mac: ENC[AES256_GCM,data:9szrriU8ewcLSl5dugVjHkfSBhYa9L+aVYha8+4DfjE1G4PwX0YGNs02qEN8XWWW9ck77Y4DZtQYBoluMOHV6oRoBSMDTkJGS1fjeVM+b+7Q3RMuSbqNcvYfkYwYYPQ4LbF4FrigiObM0zFyywCZXNB+8BpNpqkoQb3DF3h6FFY=,iv:tIBA7lcIOFGqr4yr1bCDQSp7Qo+XU5LOySyyEa4KGng=,tag:ljbgNqI3euO6CGqhCDhCkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
