kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:cJLuxS0Fy7ygic85D0c1teMzjd/BryG3NXDyXtX7he+O8M24yW9rNqxJ64d/BDs=,iv:yTQBltJZlU9yOMq3xFVZ31toR1mPxG89i6siXcpYQEQ=,tag:X4xkWaFBjOQjcPo9lZFHpA==,type:str]
    github_user: ENC[AES256_GCM,data:dOz3lpBtqc4=,iv:WIsQNfPiIUoTVi2/qRcLVI+oFoLKurDuhgQG2oZZdb8=,tag:X7WHuBAQEx7gzZp5oJhb7w==,type:str]
    github_api_token: ENC[AES256_GCM,data:1kn5HdJ5aAYIZ1plGo56NLssvC1gQpvWJyWkOFwsGIJbBv5ZqyVOhQ==,iv:h5FcEves8nxWpBoWRDm6yplUA4XVk7EgFpEmUfudwnE=,tag:16U3cvuBSxFNpzq2ttyNuw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:FUljo5X/834c7AF3,iv:O3xj/I7mpngcgDueZNcwWO4uE5Q3zD9PrKazkwDQuG0=,tag:l+huYflli2zvUr42p+BR0g==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:4jzHBaY019SV,iv:Hh13vH4E2Z0RWM+pe1yoD04Pj6jkt6s9Dc0b/SN29vI=,tag:Xkw63r4S7Wk3ua6UGbv7Ig==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:hehiG5ba7R3MxyzMOw==,iv:Pq58HxkQPgMKAc37i/VvUSkbvWADYpy/zLmhEk4KqvY=,tag:Ws8tOOtZga2+QpTzrB7OkA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:DNj97Mk=,iv:e0WbNQl9nFmZMpqHznhGgEqt4hBhr6Q14KbODhVTkBA=,tag:fuzxbULBC0Duh5GZmrSLzw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:GBzhNbNSDhoI,iv:U30Dd4ci3fCxjRmg8IqlYIcF0i4TwlsQTszHgxE000M=,tag:zjkLq/TmYVxPYgqMvza4iw==,type:str]
    objects_host: ENC[AES256_GCM,data:x+li1fliG/o+EVMhVA==,iv:8V6XhL9XQ9DvC2xVAmwQikU0B0zowpzwkbo5DtuTQYM=,tag:bGt1R4wjYoQUoia0LmcERA==,type:str]
    objects_port: ENC[AES256_GCM,data:anY=,iv:5Ry8WnRLqS8+J/+21lB0dxhPiiCJ0W66CAELQtabZhA=,tag:CXZDtnI21UKvAAyyZfImcA==,type:str]
    objects_region: ENC[AES256_GCM,data:2B1u4ULkZEZO,iv:8pqRtGdrm10qt5cDeU+EvO4RLlzvTrI42YV3AfbqFJE=,tag:DGXK2cegHRKdE0BY/VDiiQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:pfenETU=,iv:LnUYkQEBsLMiLZKh4590UfEpeXxPzNFuo+w28F+hCMw=,tag:hnh6xHvZnoERnQ/i6kOK+g==,type:str]
    objects_access_key: ENC[AES256_GCM,data:avaw96nOM+770jPbF1fNJDx6jD/REd7RppEkYzGX110=,iv:aW1AoD0/CkY4s7yU18Q114jErLBMV2sI9y3zLwlq5UY=,tag:olRkTUS2Mx5cE8X0yhkdmQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:gueUMe49WYa5mvZ2FLCZRY0ckbtYSLuTgJi2imKq99o=,iv:9bTDH3xF90FFj41db4FjRAO7vbXdXtez3xeNScobF7Y=,tag:VQX/JDxFRQTENnAiWOcydA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:Oxf2kfYEZDMdrbiXwNdnQl6XuPp8wEU7b/TU,iv:E7+Lsb+S4KraFwV9ggrMtXmNddeuWyzenXNSv2yH4e8=,tag:EUKiDSNUwzgWP86aazgn0A==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:hqBvFtqwVvxjZfuc5jKahw==,iv:+FyvAcHz06GEmwFzTmyKVVz5GEgtEcNgELg472pw910=,tag:LkA/bEkpBU3evFjHaXQWSQ==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:KFLAccHJFz9IQ/4jmBhAXrIhojieaaXhILLuA42l,iv:ztGkYE7C1AKb5NUnPfxlO7ovFakIG0Vhm/eVnecxDAs=,tag:05SteVfo3WNs6RUE4FRrfQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:fYhFNtS7YDgSoDMDSymqlQCix+aXWYLXH0amNoWT,iv:NaPQTVpkCUV1JcFD3tmNEmV50uPORLgqe1D1XwVMm0I=,tag:8PiDaVOFuwGGl3MUOzg7yg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:JXx+fgkoenzU0YBR7HBXag==,iv:uzyxu6EcrFYbEm8d6oBZTX4f7kpQuMV+Vmg+ika0r1Q=,tag:RfbUEVQS1BTBuWaUUHydyA==,type:str]
    istio_vip: ENC[AES256_GCM,data:zzIMWYXJKwqbPcqO1g==,iv:SEyw4a7qU1kGutYlo351bDkIuUfu/pjFwM3DpYE8f/4=,tag:TehxPfTin0Gh78OFMy6FJQ==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:su5YtcwavaBCXplrpKk/QRiaf3SHm3+2oxNEA8zv,iv:GiETylaMB99xO/8vELS4GkBkfnUUDFfHWWqX+DGz+AI=,tag:jT8K025i/8kweX3XB2ft0g==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:1+nCuaEk3qFGfKYDS2ZPRQlgP43y5YCXSRamnyCKCyMnt4SsUVYU/vi/88ocojkTFWHijK0rPBKIvq6X,iv:jwsk1X1bnw+ofWKUGKGa82ORnUcWYxQOvR9Y3/BF21Q=,tag:GICLL+zOzsBvxOF9XsVbCw==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:FCPLQwMTsD9nsi08aYIMqSTtnVOp35fECZDUiGRSBWGSr+ye+A==,iv:p8QI8Vw/FEyYwFuHN1BRQcE4hnBy+b0qRz5vBUI3KBo=,tag:gogsh7aDCXpDFuFPWs9DVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ds04577equqkjjmm3qs2t92u59fq4kgzqcq3khlhsg8y2p6m033qhfhj4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMnhOKzJlM2xtTnNmK0pM
            WVNHS3FlU0pSaEFsMmo0QlcxRG9BR1ZjS2k0CldrUktIQlNJMjZPNGR5RWs3S0Vj
            WEhwd28wYzdyeXBNT1NlL290dUJsLzgKLS0tIDdVZmJLNlJlTWFESEdoYUxaU3lK
            cTd1SVhHSjhSYllmOXRONFFXUnBQblkKVUHDj4q1jVNibnZM/B/lnY55sirHleWt
            Ti0rulTlW1qpEDr/7SKKyxvu2/mO7VhxKUVHvRiiTuT0LW9Myteebw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T05:10:43Z"
    mac: ENC[AES256_GCM,data:RZlCYaf3mTtODvWrzF2N6kLgIhmHOzkuDGPP0K1NBXjLc3CSE2lxVpYhQpq/gojqTnRGOXID3SW2RwyPiXKHgZgVUgb6ZX0f26K7GTA0s/gn5luZ7niTmh3YHDGzPwDBCFXaIZM26ANyBoxG2JU89s6dyHm7AXD8K3Y2EiPMeDI=,iv:MgzxN6t3W7F4hUZAJU0nhxzwNs77PV8BchUvkDmpcGI=,tag:5hZaQ/TN1V3ODsTc3u4P9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
