kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "ntnx-k8-workload"
  environment: "non-prod"
  cluster_profile: "llm-workloads"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"
  gpu_operator_version: "v23.9.0"
  nginx_ingress_version: "4.8.3"
  istio_version: "192.168.11.39"
  cert_manager_version: "v1.13.5"
  cert_manager_issuer_name: "selfsigned-cluster-issuer"
  documents_objects_bucket_name: "documents"
  milvus_version: "4.1.13"
  milvus_objects_bucket_name: "milvus"
  model: "llama2_7b_chat"
  revision: "94b07a6e30c3292b8265ed32ffdeccfdadf434a8"
  maxTokens: "4000"
  repPenalty: "1.2"
  temperature: "0.2"
  topP: "0.9"
  useExistingNFS: "false"
  kserve_version: "v0.11.2"
  knative_serving_version: "knative-v1.10.1"
  knative_istio_version: "knative-v1.10.0"
  kyverno_version: "3.1.4"
  weave_gitops_version: "4.0.36"
